-- 4. basicCard
-- 4.1. SKILL_RES_V1_TEMPLATE
INSERT INTO SKILL_RES_V1_TEMPLATE (BLOCK_ID, BLOCK_CODE, TEMPLATE_NAME, CREATOR, LAST_UPDATER)
VALUES ('6590ab5b193392115b5a7ff8', 'FP_S01_B01', '테스트 템플릿(single basicCard)', 'admin', 'admin')
;

-- 4.2. SKILL_RES_V1_TEMPLATE_OUTPUT
INSERT INTO SKILL_RES_V1_TEMPLATE_OUTPUT (TEMPLATE_ID, OUTPUT_ORD, OUTPUT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('B4B715E3EDC611EEB5380A48BC1A5EE1'), 1, '테스트 아웃풋(single basicCard)', 'admin', 'admin')
;

-- 4.3. SKILL_RES_V1_TEMPLATE_COMPONENT
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('C5E0B535EDC611EEB5380A48BC1A5EE1'), 'basicCard', '테스트 컴포넌트(single basicCard)', 'admin', 'admin')
;

-- 4.4. SKILL_RES_V1_TEMPLATE_BASICCARD
INSERT INTO SKILL_RES_V1_TEMPLATE_BASICCARD (COMPONENT_ID, TITLE, `DESC`, THUMB, CREATOR, LAST_UPDATER)
VALUES (UNHEX('2AAF4950EDC711EEB5380A48BC1A5EE1'), '테스트 타이틀', '테스트 상세 설명입니다.', 'http://localhost:8080/resources/img/test.jpg', 'admin', 'admin')
;

-- 4.5. SKILL_RES_V1_TEMPLATE_COMPONENT_BTN
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('2AAF4950EDC711EEB5380A48BC1A5EE1'), '테스트 라벨(basicCard)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

-- 4.6. SKILL_RES_V1_TEMPLATE_QRPL
INSERT INTO SKILL_RES_V1_TEMPLATE_QRPL (TEMPLATE_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('B4B715E3EDC611EEB5380A48BC1A5EE1'), '테스트 라벨(basicCard)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;