-- 7. itemCard
-- 7.1. SKILL_RES_V1_TEMPLATE
INSERT INTO SKILL_RES_V1_TEMPLATE (BLOCK_ID, BLOCK_CODE, TEMPLATE_NAME, CREATOR, LAST_UPDATER)
VALUES ('6590ab5b193392115b5a7ff8', 'FP_S01_B01', '테스트 템플릿(single itemCard)', 'admin', 'admin')
;

-- 7.2. SKILL_RES_V1_TEMPLATE_OUTPUT
INSERT INTO SKILL_RES_V1_TEMPLATE_OUTPUT (TEMPLATE_ID, OUTPUT_ORD, OUTPUT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('FF854FEBEF0A11EEB5380A48BC1A5EE1'), 1, '테스트 아웃풋(single itemCard)', 'admin', 'admin')
;

-- 7.3. SKILL_RES_V1_TEMPLATE_COMPONENT
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('0F6FECDAEF0B11EEB5380A48BC1A5EE1'), 'itemCard', '테스트 컴포넌트(single itemCard)', 'admin', 'admin')
;

-- 7.4. SKILL_RES_V1_TEMPLATE_LISTCARD , SKILL_RES_V1_TEMPLATE_LISTCARD_LISTITEM
INSERT INTO SKILL_RES_V1_TEMPLATE_ITEMCARD (COMPONENT_ID, THUMB_YN, THUMB_IMG_URL, HEAD_YN, HEAD_TITLE, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('18488D0CEF0B11EEB5380A48BC1A5EE1'), 'Y', 'http://localhost:8080/resources/img/test.jpg', 'Y', '테스트 헤더 제목', '테스트 제목', '테스트 설명입니다.', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_ITEMCARD_ITEMLIST (COMPONENT_ID, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('18488D0CEF0B11EEB5380A48BC1A5EE1'), '테스트 제목', '테스트 설명입니다.', 'admin', 'admin')
;

-- 7.5. SKILL_RES_V1_TEMPLATE_COMPONENT_BTN
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('18488D0CEF0B11EEB5380A48BC1A5EE1'), '테스트 라벨(itemCard)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

-- 7.6. SKILL_RES_V1_TEMPLATE_QRPL
INSERT INTO SKILL_RES_V1_TEMPLATE_QRPL (TEMPLATE_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('FF854FEBEF0A11EEB5380A48BC1A5EE1'), '테스트 라벨(itemCard)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;