-- 1. simpleText
-- 1.1. SKILL_RES_V1_TEMPLATE
INSERT INTO SKILL_RES_V1_TEMPLATE (BLOCK_ID, BLOCK_CODE, TEMPLATE_NAME, CREATOR, LAST_UPDATER)
VALUES ('6590ab5b193392115b5a7ff8', 'FP_S01_B01', '테스트 템플릿(single simpleText)', 'admin', 'admin')
;

-- 1.2. SKILL_RES_V1_TEMPLATE_OUTPUT
INSERT INTO SKILL_RES_V1_TEMPLATE_OUTPUT (TEMPLATE_ID, OUTPUT_ORD, OUTPUT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('4144051BEDB711EEB5380A48BC1A5EE1'), 1, '테스트 아웃풋(single simpleText)', 'admin', 'admin')
;

-- 1.3. SKILL_RES_V1_TEMPLATE_COMPONENT
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('6BDD5A89EDB711EEB5380A48BC1A5EE1'), 'simpleText', '테스트 컴포넌트(single simpleText)', 'admin', 'admin')
;

-- 1.4. SKILL_RES_V1_TEMPLATE_SIMPLETEXT
INSERT INTO SKILL_RES_V1_TEMPLATE_SIMPLETEXT (COMPONENT_ID, TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('72135D7EEDB711EEB5380A48BC1A5EE1'), '테스트 텍스트 입니다.', 'admin', 'admin')
;

-- 1.5. SKILL_RES_V1_TEMPLATE_COMPONENT_BTN
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('72135D7EEDB711EEB5380A48BC1A5EE1'), '테스트 라벨', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

-- 1.6. SKILL_RES_V1_TEMPLATE_QRPL
INSERT INTO SKILL_RES_V1_TEMPLATE_QRPL (TEMPLATE_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('4144051BEDB711EEB5380A48BC1A5EE1'), '테스트 라벨(simpleText)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;