-- 2. simpleImage
-- 2.1. SKILL_RES_V1_TEMPLATE
INSERT INTO SKILL_RES_V1_TEMPLATE (BLOCK_ID, BLOCK_CODE, TEMPLATE_NAME, CREATOR, LAST_UPDATER)
VALUES ('6590ab5b193392115b5a7ff8', 'FP_S01_B01', '테스트 템플릿(single simpleImage)', 'admin', 'admin')
;

-- 2.2. SKILL_RES_V1_TEMPLATE_OUTPUT
INSERT INTO SKILL_RES_V1_TEMPLATE_OUTPUT (TEMPLATE_ID, OUTPUT_ORD, OUTPUT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('7F2AB54DEDAC11EEB5380A48BC1A5EE1'), 1, '테스트 아웃풋(single simpleImage)', 'admin', 'admin')
;

-- 2.3. SKILL_RES_V1_TEMPLATE_COMPONENT
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('9B418C29EDAC11EEB5380A48BC1A5EE1'), 'simpleImage', '테스트 컴포넌트(single simpleImage)', 'admin', 'admin')
;

-- 2.4. SKILL_RES_V1_TEMPLATE_SIMPLEIMAGE
INSERT INTO SKILL_RES_V1_TEMPLATE_SIMPLEIMAGE (COMPONENT_ID, IMG_URL, ALT_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('AC8C4CF3EDAC11EEB5380A48BC1A5EE1'), 'http://localhost:8080/resources/img/test.jpg', '대체 텍스트 입니다.', 'admin', 'admin')
;

-- 2.5. SKILL_RES_V1_TEMPLATE_COMPONENT_BTN
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('393B55B3EC3911EEB5380A48BC1A5EE1'), '테스트 라벨', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

-- 2.6. SKILL_RES_V1_TEMPLATE_QRPL
INSERT INTO SKILL_RES_V1_TEMPLATE_QRPL (TEMPLATE_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('7F2AB54DEDAC11EEB5380A48BC1A5EE1'), '테스트 라벨', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;