-- 8. carousel > textCard
-- 8.1. SKILL_RES_V1_TEMPLATE
INSERT INTO SKILL_RES_V1_TEMPLATE (BLOCK_ID, BLOCK_CODE, TEMPLATE_NAME, CREATOR, LAST_UPDATER)
VALUES ('6590ab5b193392115b5a7ff8', 'FP_S01_B01', '테스트 템플릿(carousel > textCard)', 'admin', 'admin')
;

-- 8.2. SKILL_RES_V1_TEMPLATE_OUTPUT
INSERT INTO SKILL_RES_V1_TEMPLATE_OUTPUT (TEMPLATE_ID, OUTPUT_ORD, OUTPUT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('6C5D0ABBEF2511EEB5380A48BC1A5EE1'), 1, '테스트 아웃풋(carousel > textCard)', 'admin', 'admin')
;

-- 8.3. SKILL_RES_V1_TEMPLATE_COMPONENT
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('7D879BEEEF2511EEB5380A48BC1A5EE1'), 'carousel', '테스트 컴포넌트(carousel > textCard)', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (NULL, 'textCard', '테스트 컴포넌트(carousel > textCard > 1)', 'admin', 'admin') -- carousel item 에 해당하는 component 의 경우 output_id = null
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (NULL, 'textCard', '테스트 컴포넌트(carousel > textCard > 2)', 'admin', 'admin') -- carousel item 에 해당하는 component 의 경우 output_id = null
;

-- 8.4. SKILL_RES_V1_TEMPLATE_CAROUSEL , SKILL_RES_V1_TEMPLATE_TEXTCARD
INSERT INTO SKILL_RES_V1_TEMPLATE_CAROUSEL (COMPONENT_ID, CARD_TYPE, HEADER_TITLE, HEADER_DESC, HEADER_THUMB, CREATOR, LAST_UPDATER)
VALUES (UNHEX('96561374EF2511EEB5380A48BC1A5EE1'), 'textCard', '테스트 헤더 제목', '테스트 헤더 설명입니다.', 'http://localhost:8080/resources/img/test.jpg', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_TEXTCARD (CAROUSEL_ID, COMPONENT_ID, CARD_ORD, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('F19C7476EF2511EEB5380A48BC1A5EE1'), UNHEX('6861AD2AF03111EEB5380A48BC1A5EE1'), 1, '테스트 제목1', '테스트 설명입니다.1', 'admin', 'admin')  -- carousel item 에 해당하는 component card 의 경우 carousel_id 값이 필
;

INSERT INTO SKILL_RES_V1_TEMPLATE_TEXTCARD (CAROUSEL_ID, COMPONENT_ID, CARD_ORD, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('F19C7476EF2511EEB5380A48BC1A5EE1'), UNHEX('693B3C9FF03111EEB5380A48BC1A5EE1'), 2, '테스트 제목2', '테스트 설명입니다.2', 'admin', 'admin')  -- carousel item 에 해당하는 component card 의 경우 carousel_id 값이 필
;

-- 8.5. SKILL_RES_V1_TEMPLATE_COMPONENT_BTN
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('6861AD2AF03111EEB5380A48BC1A5EE1'), '테스트 라벨(textCard > 1)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('693B3C9FF03111EEB5380A48BC1A5EE1'), '테스트 라벨(textCard > 2)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

-- 8.6. SKILL_RES_V1_TEMPLATE_QRPL
INSERT INTO SKILL_RES_V1_TEMPLATE_QRPL (TEMPLATE_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('6C5D0ABBEF2511EEB5380A48BC1A5EE1'), '테스트 라벨(carousel > textCard)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;