-- 12. carousel > itemCard
-- 12.1. SKILL_RES_V1_TEMPLATE
INSERT INTO SKILL_RES_V1_TEMPLATE (BLOCK_ID, BLOCK_CODE, TEMPLATE_NAME, CREATOR, LAST_UPDATER)
VALUES ('6590ab5b193392115b5a7ff8', 'FP_S01_B01', '테스트 템플릿(carousel > itemCard)', 'admin', 'admin')
;

-- 12.2. SKILL_RES_V1_TEMPLATE_OUTPUT
INSERT INTO SKILL_RES_V1_TEMPLATE_OUTPUT (TEMPLATE_ID, OUTPUT_ORD, OUTPUT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('FF669F16F48D11EEB5380A48BC1A5EE1'), 1, '테스트 아웃풋(carousel > itemCard)', 'admin', 'admin')
;

-- 12.3. SKILL_RES_V1_TEMPLATE_COMPONENT
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('1305FFC3F48E11EEB5380A48BC1A5EE1'), 'carousel', '테스트 컴포넌트(carousel > itemCard)', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (NULL, 'itemCard', '테스트 컴포넌트(carousel > itemCard > 1)', 'admin', 'admin') -- carousel item 에 해당하는 component 의 경우 output_id = null
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (NULL, 'itemCard', '테스트 컴포넌트(carousel > itemCard > 2)', 'admin', 'admin') -- carousel item 에 해당하는 component 의 경우 output_id = null
;

-- 12.4. SKILL_RES_V1_TEMPLATE_CAROUSEL , SKILL_RES_V1_TEMPLATE_LISTCARD , SKILL_RES_V1_TEMPLATE_LISTCARD_LISTITEM
INSERT INTO SKILL_RES_V1_TEMPLATE_CAROUSEL (COMPONENT_ID, CARD_TYPE, HEADER_TITLE, HEADER_DESC, HEADER_THUMB, CREATOR, LAST_UPDATER)
VALUES (UNHEX('258E24C1F48E11EEB5380A48BC1A5EE1'), 'itemCard', '테스트 헤더 제목', '테스트 헤더 설명입니다.', 'http://localhost:8080/resources/img/test.jpg', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_ITEMCARD (CAROUSEL_ID, COMPONENT_ID, CARD_ORD, THUMB_YN, THUMB_IMG_URL, HEAD_YN, HEAD_TITLE, IMGTITLE_YN, IMGTITLE_TITLE, IMGTITLE_DESC, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('68132C84F48E11EEB5380A48BC1A5EE1'), UNHEX('470993D4F48E11EEB5380A48BC1A5EE1'), 1, 'Y', 'http://localhost:8080/resources/img/test.jpg', 'Y', '테스트 헤더 제목', 'Y', '테스트 이미지타이틀 제목', '테스트 이미지타이틀 설명입니다.', '테스트 제목', '테스트 설명입니다.', 'admin', 'admin')  -- carousel item 에 해당하는 component card 의 경우 carousel_id 값이 필
;

INSERT INTO SKILL_RES_V1_TEMPLATE_ITEMCARD (CAROUSEL_ID, COMPONENT_ID, CARD_ORD, THUMB_YN, THUMB_IMG_URL, PROFILE_YN, PROFILE_TITLE, ITEMLIST_SUMMARY_YN, ITEMLIST_SUMMARY_TITLE, ITEMLIST_SUMMARY_DESC, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('68132C84F48E11EEB5380A48BC1A5EE1'), UNHEX('47ABD9EDF48E11EEB5380A48BC1A5EE1'), 2, 'Y', 'http://localhost:8080/resources/img/test.jpg', 'Y', '테스트 프로필 제목', 'Y', '테스트 아이템리스트 서머리 제목', '테스트 아이템리스트 서머리 설명입니다.', '테스트 제목', '테스트 설명입니다.', 'admin', 'admin')  -- carousel item 에 해당하는 component card 의 경우 carousel_id 값이 필
;

INSERT INTO SKILL_RES_V1_TEMPLATE_ITEMCARD_ITEMLIST (COMPONENT_ID, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('470993D4F48E11EEB5380A48BC1A5EE1'), '테스트 제목', '테스트 설명입니다.(carousel > itemCard > 1 > itemList)', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_ITEMCARD_ITEMLIST (COMPONENT_ID, TITLE, `DESC`, CREATOR, LAST_UPDATER)
VALUES (UNHEX('47ABD9EDF48E11EEB5380A48BC1A5EE1'), '테스트 제목', '테스트 설명입니다.(carousel > itemCard > 2 > itemList)', 'admin', 'admin')
;

-- 12.5. SKILL_RES_V1_TEMPLATE_COMPONENT_BTN
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('470993D4F48E11EEB5380A48BC1A5EE1'), '테스트 라벨(carousel > itemCard > 1)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('47ABD9EDF48E11EEB5380A48BC1A5EE1'), '테스트 라벨(carousel > itemCard > 2)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

-- 12.6. SKILL_RES_V1_TEMPLATE_QRPL
INSERT INTO SKILL_RES_V1_TEMPLATE_QRPL (TEMPLATE_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('FF669F16F48D11EEB5380A48BC1A5EE1'), '테스트 라벨(carousel > itemCard)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;