-- 10. carousel > commerceCard
-- 10.1. SKILL_RES_V1_TEMPLATE
INSERT INTO SKILL_RES_V1_TEMPLATE (BLOCK_ID, BLOCK_CODE, TEMPLATE_NAME, CREATOR, LAST_UPDATER)
VALUES ('6590ab5b193392115b5a7ff8', 'FP_S01_B01', '테스트 템플릿(carousel > commerceCard)', 'admin', 'admin')
;

-- 10.2. SKILL_RES_V1_TEMPLATE_OUTPUT
INSERT INTO SKILL_RES_V1_TEMPLATE_OUTPUT (TEMPLATE_ID, OUTPUT_ORD, OUTPUT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('0F4C22C4F34811EEB5380A48BC1A5EE1'), 1, '테스트 아웃풋(carousel > commerceCard)', 'admin', 'admin')
;

-- 10.3. SKILL_RES_V1_TEMPLATE_COMPONENT
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (UNHEX('1E7BBB20F34811EEB5380A48BC1A5EE1'), 'carousel', '테스트 컴포넌트(carousel > commerceCard)', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (NULL, 'commerceCard', '테스트 컴포넌트(carousel > commerceCard > 1)', 'admin', 'admin') -- carousel item 에 해당하는 component 의 경우 output_id = null
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT (OUTPUT_ID, COMPONENT_TYPE, COMPONENT_NAME, CREATOR, LAST_UPDATER)
VALUES (NULL, 'commerceCard', '테스트 컴포넌트(carousel > commerceCard > 2)', 'admin', 'admin') -- carousel item 에 해당하는 component 의 경우 output_id = null
;

-- 10.4. SKILL_RES_V1_TEMPLATE_CAROUSEL , SKILL_RES_V1_TEMPLATE_TEXTCARD
INSERT INTO SKILL_RES_V1_TEMPLATE_CAROUSEL (COMPONENT_ID, CARD_TYPE, HEADER_TITLE, HEADER_DESC, HEADER_THUMB, CREATOR, LAST_UPDATER)
VALUES (UNHEX('2D2AF490F34811EEB5380A48BC1A5EE1'), 'commerceCard', '테스트 헤더 제목', '테스트 헤더 설명입니다.', 'http://localhost:8080/resources/img/test.jpg', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMMERCECARD (CAROUSEL_ID, COMPONENT_ID, CARD_ORD, TITLE, `DESC`, PRICE, CURRENCY, DISCOUNT, DISCOUNT_RATE, DISCOUNTED_PRICE, THUMB_IMG_URL, CREATOR, LAST_UPDATER)
VALUES (UNHEX('585544A5F34811EEB5380A48BC1A5EE1'), UNHEX('3CEC2306F34811EEB5380A48BC1A5EE1'), 1, '테스트 타이틀1', 'carousel > commerceCard > 1 테스트 상세 설명입니다.', 10000, 'won', 1000, 10, 9000, 'http://localhost:8080/resources/img/test.jpg', 'admin', 'admin')  -- carousel item 에 해당하는 component card 의 경우 carousel_id 값이 필
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMMERCECARD (CAROUSEL_ID, COMPONENT_ID, CARD_ORD, TITLE, `DESC`, PRICE, CURRENCY, DISCOUNT, DISCOUNT_RATE, DISCOUNTED_PRICE, THUMB_IMG_URL, CREATOR, LAST_UPDATER)
VALUES (UNHEX('585544A5F34811EEB5380A48BC1A5EE1'), UNHEX('3D8899E5F34811EEB5380A48BC1A5EE1'), 2, '테스트 타이틀2', 'carousel > commerceCard > 2 테스트 상세 설명입니다.', 10000, 'won', 1000, 10, 9000, 'http://localhost:8080/resources/img/test.jpg', 'admin', 'admin')  -- carousel item 에 해당하는 component card 의 경우 carousel_id 값이 필
;

-- 10.5. SKILL_RES_V1_TEMPLATE_COMPONENT_BTN
INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('3CEC2306F34811EEB5380A48BC1A5EE1'), '테스트 라벨(commerceCard > 1)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

INSERT INTO SKILL_RES_V1_TEMPLATE_COMPONENT_BTN (COMPONENT_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('3D8899E5F34811EEB5380A48BC1A5EE1'), '테스트 라벨(commerceCard > 2)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;

-- 10.6. SKILL_RES_V1_TEMPLATE_QRPL
INSERT INTO SKILL_RES_V1_TEMPLATE_QRPL (TEMPLATE_ID, LABEL, ACTION, MESSAGE_TEXT, CREATOR, LAST_UPDATER)
VALUES (UNHEX('0F4C22C4F34811EEB5380A48BC1A5EE1'), '테스트 라벨(carousel > commerceCard)', 'message', '테스트 메시지 입니다.', 'admin', 'admin')
;
